[tool]
[tool.poetry]
name = "appxcodingchallenge"
version = "0.1"
description = "appxcodingchallenge"
authors = ["Your Name <you@example.com>"]
[tool.poetry.dependencies]
flask = "^1.1.2"
python = "^3.8"
